# Generated by Django 3.1.1 on 2022-05-27 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(default='2022-05-09')),
                ('hora_inicio', models.TimeField(default='09:00:00')),
                ('hora_fim', models.TimeField(default='10:00:00')),
                ('max_alunos', models.IntegerField(default=8)),
                ('numero_alunos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agendas',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
                ('contato', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('agendas', models.ManyToManyField(to='aulas.Agenda')),
                ('username', models.ForeignKey(default='TESTE1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='aulas.aula'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='aulas_usuar_usernam_d96d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['data_aula'], name='aulas_agend_data_au_ac723a_idx'),
        ),
    ]
