# Generated by Django 3.1.1 on 2022-05-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('alternativa1', models.CharField(max_length=100)),
                ('alternativa2', models.CharField(max_length=100)),
                ('alternativa3', models.CharField(max_length=100)),
                ('alternativa4', models.CharField(max_length=100)),
                ('resposta', models.CharField(max_length=64)),
                ('explica', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='schedule',
        ),
    ]
