# Generated by Django 3.1.1 on 2022-05-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20220527_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='agendas',
            field=models.ManyToManyField(blank=True, related_name='aulas', to='aulas.Agenda'),
        ),
    ]
