# Generated by Django 3.1.1 on 2022-05-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20220509_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionario',
        ),
    ]
