# Generated by Django 3.1.1 on 2022-05-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_auto_20220527_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
